#line 2 "statement_list_lex.yy.cpp"

#line 4 "statement_list_lex.yy.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer yystatement_list_create_buffer
#define yy_delete_buffer yystatement_list_delete_buffer
#define yy_scan_buffer yystatement_list_scan_buffer
#define yy_scan_string yystatement_list_scan_string
#define yy_scan_bytes yystatement_list_scan_bytes
#define yy_init_buffer yystatement_list_init_buffer
#define yy_flush_buffer yystatement_list_flush_buffer
#define yy_load_buffer_state yystatement_list_load_buffer_state
#define yy_switch_to_buffer yystatement_list_switch_to_buffer
#define yypush_buffer_state yystatement_listpush_buffer_state
#define yypop_buffer_state yystatement_listpop_buffer_state
#define yyensure_buffer_stack yystatement_listensure_buffer_stack
#define yy_flex_debug yystatement_list_flex_debug
#define yyin yystatement_listin
#define yyleng yystatement_listleng
#define yylex yystatement_listlex
#define yylineno yystatement_listlineno
#define yyout yystatement_listout
#define yyrestart yystatement_listrestart
#define yytext yystatement_listtext
#define yywrap yystatement_listwrap
#define yyalloc yystatement_listalloc
#define yyrealloc yystatement_listrealloc
#define yyfree yystatement_listfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define yystatement_list_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer yystatement_list_create_buffer
#endif

#ifdef yy_delete_buffer
#define yystatement_list_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer yystatement_list_delete_buffer
#endif

#ifdef yy_scan_buffer
#define yystatement_list_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer yystatement_list_scan_buffer
#endif

#ifdef yy_scan_string
#define yystatement_list_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string yystatement_list_scan_string
#endif

#ifdef yy_scan_bytes
#define yystatement_list_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes yystatement_list_scan_bytes
#endif

#ifdef yy_init_buffer
#define yystatement_list_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer yystatement_list_init_buffer
#endif

#ifdef yy_flush_buffer
#define yystatement_list_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer yystatement_list_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define yystatement_list_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state yystatement_list_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define yystatement_list_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer yystatement_list_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define yystatement_listpush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state yystatement_listpush_buffer_state
#endif

#ifdef yypop_buffer_state
#define yystatement_listpop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state yystatement_listpop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define yystatement_listensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack yystatement_listensure_buffer_stack
#endif

#ifdef yylex
#define yystatement_listlex_ALREADY_DEFINED
#else
#define yylex yystatement_listlex
#endif

#ifdef yyrestart
#define yystatement_listrestart_ALREADY_DEFINED
#else
#define yyrestart yystatement_listrestart
#endif

#ifdef yylex_init
#define yystatement_listlex_init_ALREADY_DEFINED
#else
#define yylex_init yystatement_listlex_init
#endif

#ifdef yylex_init_extra
#define yystatement_listlex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra yystatement_listlex_init_extra
#endif

#ifdef yylex_destroy
#define yystatement_listlex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy yystatement_listlex_destroy
#endif

#ifdef yyget_debug
#define yystatement_listget_debug_ALREADY_DEFINED
#else
#define yyget_debug yystatement_listget_debug
#endif

#ifdef yyset_debug
#define yystatement_listset_debug_ALREADY_DEFINED
#else
#define yyset_debug yystatement_listset_debug
#endif

#ifdef yyget_extra
#define yystatement_listget_extra_ALREADY_DEFINED
#else
#define yyget_extra yystatement_listget_extra
#endif

#ifdef yyset_extra
#define yystatement_listset_extra_ALREADY_DEFINED
#else
#define yyset_extra yystatement_listset_extra
#endif

#ifdef yyget_in
#define yystatement_listget_in_ALREADY_DEFINED
#else
#define yyget_in yystatement_listget_in
#endif

#ifdef yyset_in
#define yystatement_listset_in_ALREADY_DEFINED
#else
#define yyset_in yystatement_listset_in
#endif

#ifdef yyget_out
#define yystatement_listget_out_ALREADY_DEFINED
#else
#define yyget_out yystatement_listget_out
#endif

#ifdef yyset_out
#define yystatement_listset_out_ALREADY_DEFINED
#else
#define yyset_out yystatement_listset_out
#endif

#ifdef yyget_leng
#define yystatement_listget_leng_ALREADY_DEFINED
#else
#define yyget_leng yystatement_listget_leng
#endif

#ifdef yyget_text
#define yystatement_listget_text_ALREADY_DEFINED
#else
#define yyget_text yystatement_listget_text
#endif

#ifdef yyget_lineno
#define yystatement_listget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno yystatement_listget_lineno
#endif

#ifdef yyset_lineno
#define yystatement_listset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno yystatement_listset_lineno
#endif

#ifdef yywrap
#define yystatement_listwrap_ALREADY_DEFINED
#else
#define yywrap yystatement_listwrap
#endif

#ifdef yyalloc
#define yystatement_listalloc_ALREADY_DEFINED
#else
#define yyalloc yystatement_listalloc
#endif

#ifdef yyrealloc
#define yystatement_listrealloc_ALREADY_DEFINED
#else
#define yyrealloc yystatement_listrealloc
#endif

#ifdef yyfree
#define yystatement_listfree_ALREADY_DEFINED
#else
#define yyfree yystatement_listfree
#endif

#ifdef yytext
#define yystatement_listtext_ALREADY_DEFINED
#else
#define yytext yystatement_listtext
#endif

#ifdef yyleng
#define yystatement_listleng_ALREADY_DEFINED
#else
#define yyleng yystatement_listleng
#endif

#ifdef yyin
#define yystatement_listin_ALREADY_DEFINED
#else
#define yyin yystatement_listin
#endif

#ifdef yyout
#define yystatement_listout_ALREADY_DEFINED
#else
#define yyout yystatement_listout
#endif

#ifdef yy_flex_debug
#define yystatement_list_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug yystatement_list_flex_debug
#endif

#ifdef yylineno
#define yystatement_listlineno_ALREADY_DEFINED
#else
#define yylineno yystatement_listlineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yystatement_listwrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 113
#define YY_END_OF_BUFFER 114
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[315] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  114,    1,  113,    3,  113,    2,   47,  113,
       49,  113,  113,   83,   83,   83,    2,  113,   48,  113,
       35,   94,   94,   94,   94,   94,   94,   94,   94,   26,
       94,   37,   33,   32,   27,   94,   39,  113,   94,   94,
       96,  113,  113,   99,  113,  101,  108,  113,  113,  113,
      113,  113,  113,  113,  113,  109,  112,  113,  110,    0,
       72,   52,   62,   83,   70,   50,   60,   71,   51,   61,
       73,   53,   63,    0,   83,   83,    0,    4,    0,    0,
       77,   57,   67,    0,    0,   76,   56,   66,   41,   94,

       95,   36,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   81,   80,    0,   94,   94,   43,   38,   94,
       94,   94,   94,   94,   94,   94,   94,   45,   40,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   94,   93,    0,    0,   89,   79,   59,
       69,   75,   55,   65,   74,   54,   64,   78,   58,   68,
       42,   94,   94,   94,   31,   94,   94,   94,   94,   94,
       94,   21,   82,    0,   85,   94,   29,   34,   44,   94,
       30,    5,   94,   94,   15,   94,   94,   46,   97,    0,
      100,  103,    0,    0,    0,  104,    0,    0,    0,  111,

        0,   83,   86,   94,   23,   28,   94,   22,   94,   94,
       94,    0,   94,   24,   94,   92,    0,   94,   94,   25,
        0,  106,  105,    0,  107,  102,  102,  111,    6,    0,
       94,   94,   94,    0,   84,   84,   84,   94,   20,    0,
       94,   94,   94,   94,    0,   85,   85,   94,   94,   94,
       84,   84,    0,   94,    0,   94,   94,   94,   94,    0,
       85,   85,    0,   94,   18,   94,    0,    0,   90,   19,
        0,   94,   94,   94,   94,    7,   98,    0,   91,   94,
       10,   87,    0,   94,   94,   94,   17,   88,   94,   94,
        0,   12,   94,   94,   94,   94,    0,   14,   13,   94,

       94,    0,   11,   94,   16,   94,   94,   94,    8,   94,
       94,   94,    9,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    7,    1,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
       19,   19,   19,   20,   19,   19,   19,   21,   22,   23,
       24,   25,    1,    1,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       33,   42,   43,   44,   45,   46,   47,   48,   33,   33,
        1,    1,    1,    1,   49,    1,   50,   51,   51,   52,

       53,   54,   33,   33,   55,   33,   33,   56,   33,   57,
       58,   33,   33,   59,   60,   61,   62,   33,   33,   33,
       33,   33,    1,   63,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[64] =
    {   0,
        1,    2,    2,    1,    2,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    1,    4,    4,    4,    4,    4,
        5,    1,    1,    1,    1,    6,    6,    6,    6,    6,
        6,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    5,    6,
        6,    6,    6,    6,    7,    7,    7,    7,    7,    7,
        7,    7,    1
    } ;

static const flex_int16_t yy_base[326] =
    {   0,
        0,    0,    0,    0,   62,   66,   70,   74,   95,    0,
      157,  177,  399,  971,  971,  971,    0,  971,  971,   51,
       94,  101,   52,  128,  148,  185,  368,  158,  347,  182,
       95,   74,  199,  117,  132,  164,   80,  200,  202,  149,
      205,  207,  133,  210,  229,  235,  221,  334,  233,  211,
      971,    0,  315,  971,    0,  971,  971,    0,  287,  310,
      201,  279,  257,  175,  226,  971,  971,  261,  971,  303,
      971,  971,  971,  278,  971,  971,  971,  971,  971,  971,
      971,  971,  971,  283,  298,  305,   89,  971,  240,  297,
      971,  971,  971,  298,  299,  971,  971,  971,  971,  142,

      971,  241,  321,  299,  322,  326,  327,  329,  330,  341,
      265,  344,  348,  352,  359,  353,  373,  971,  374,  375,
      377,  380,  382,  383,  381,  385,  392,  971,  399,  285,
      300,  262,  285,  415,  229,  227,   52,  211,  208,  301,
      374,  422,  234,  971,  432,  442,    0,  250,  971,  971,
      971,  971,  971,  971,  971,  971,  971,  971,  971,  971,
      971,  435,  401,  446,  455,  456,  457,  458,  460,  463,
      464,  465,  466,  476,  492,  467,  481,  496,  971,  498,
      505,  507,  508,  513,  519,  514,  517,  971,  971,  195,
      971,  530,  177,  161,  493,  971,  156,  502,  521,  542,

      559,  569,    0,  531,  516,  559,  584,  574,  575,  583,
      586,  598,  589,  591,  611,  612,  160,  614,  616,  617,
      140,  971,  971,  593,  971,  971,  596,  971,  619,  644,
      623,  626,  645,  653,  658,  664,  679,  679,  680,   93,
      681,  682,  683,  684,  105,  690,  712,  704,  714,  715,
      728,  733,  677,  733,   88,  749,  750,  751,  752,   77,
      758,  786,  698,  758,  759,  760,  796,    0,  700,  774,
       48,  775,  779,  776,  780,  802,  971,    0,  808,  810,
      814,    0,   46,  818,  819,  820,  821,    0,  822,  824,
       61,  825,  826,  828,  829,  836,   45,  840,  845,  847,

      859,   39,  866,  867,  971,  869,  868,  870,  871,  873,
      877,  876,  885,  971,  915,  922,  929,  934,  938,  945,
      952,  954,  958,  961,  964
    } ;

static const flex_int16_t yy_def[326] =
    {   0,
      315,  315,  314,    3,  316,  316,  316,  316,  316,    9,
      316,  316,  314,  314,  314,  314,  317,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  319,  318,  318,
      314,  320,  314,  314,  321,  314,  314,  322,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  317,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  318,

      314,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  314,  318,  318,  314,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  314,  318,  319,
      320,  314,  321,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  323,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  314,  314,  318,  318,  318,  314,  318,
      318,  318,  318,  318,  318,  318,  318,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,

      314,  314,  323,  318,  318,  318,  318,  318,  318,  318,
      318,  314,  318,  318,  318,  318,  314,  318,  318,  318,
      314,  314,  314,  314,  314,  314,  314,  314,  318,  314,
      318,  318,  318,  314,  314,  314,  314,  318,  318,  314,
      318,  318,  318,  318,  314,  314,  314,  318,  318,  318,
      314,  314,  314,  318,  314,  318,  318,  318,  318,  314,
      314,  314,  314,  318,  318,  318,  314,  324,  314,  318,
      314,  318,  318,  318,  318,  318,  314,  325,  314,  318,
      318,  324,  314,  318,  318,  318,  318,  325,  318,  318,
      314,  318,  318,  318,  318,  318,  314,  318,  318,  318,

      318,  314,  318,  318,  314,  318,  318,  318,  318,  318,
      318,  318,  318,    0,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314
    } ;

static const flex_int16_t yy_nxt[1035] =
    {   0,
       15,   16,   16,   16,   17,   18,   15,   18,   19,   20,
       21,   18,   22,   18,   23,   24,   25,   26,   24,   24,
       27,   18,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   37,   38,   39,   37,   40,   37,   41,   42,
       37,   43,   44,   45,   37,   46,   37,   47,   48,   37,
       37,   37,   37,   49,   37,   37,   37,   37,   37,   37,
       50,   37,   15,   51,   51,   51,   52,   51,   51,   51,
       52,   54,   54,   54,   55,   54,   54,   54,   55,   71,
       81,  314,  305,  302,   72,   82,  297,  314,  195,  291,
      283,   53,   73,   83,  101,   53,   56,   57,   56,   56,

      101,   58,   99,  103,  148,  148,   56,  195,  277,   74,
       74,   74,   74,   74,  195,  101,   74,   74,   74,   74,
       74,   59,   75,   60,  314,   61,  271,   76,   62,   78,
      260,  104,  255,  102,   79,   77,   63,  101,   64,  314,
      314,   84,   80,   74,   74,   74,   74,   74,   61,  314,
      107,  148,  101,  101,  115,   64,  314,   65,   66,   67,
       66,   84,  101,   85,   74,   74,   74,   86,   66,  101,
      108,  314,   68,   68,   68,   68,   68,   69,   66,   67,
       66,   89,   90,  245,  101,  120,   91,  240,   66,  109,
       87,   92,   68,   68,   68,   68,   68,   69,   84,   93,

       74,   74,   74,   74,   74,   95,  314,  314,  110,  314,
       96,  225,  314,  109,  118,   97,  140,  314,  314,  101,
      101,  223,  101,   98,  105,  101,  137,  101,  128,  113,
      101,  101,  222,  140,  116,  106,  314,  140,  111,  121,
      314,  101,  314,  221,  117,  119,  114,  142,  161,  101,
      137,  137,  124,  101,  122,  101,  112,  197,  109,  129,
      125,  101,  123,  137,  126,  148,  148,  140,  149,  124,
      124,  196,  314,  150,  142,  137,  143,  143,  143,  143,
      143,  151,  109,  194,  140,  101,  193,  124,  141,  191,
      190,   84,  127,   74,   74,   74,   74,   74,  145,  145,

      145,  145,  145,  146,  189,  101,  314,  144,  171,  139,
      147,   84,  148,   74,   74,   74,   74,   74,   84,  101,
       74,   74,   74,   74,   74,  152,  155,  158,  314,  314,
      153,  156,  159,  314,  314,  138,  314,  314,  154,  157,
      160,  101,  101,  136,  135,  198,  101,  101,  314,  101,
      101,  314,  162,  132,  101,  314,  163,  168,  164,  314,
      314,  101,  198,  198,  101,  166,  169,  165,  101,  174,
       94,  174,  101,  101,  175,  175,  175,  175,  175,  170,
      314,  179,  314,  167,  314,  169,  173,  314,  314,  314,
      314,   88,  314,  101,  101,  101,  176,  101,  314,  314,

      101,  101,  101,  101,  172,  101,  188,  314,  314,  314,
      195,  182,  101,  177,  314,  314,  178,  314,  198,  101,
      181,  101,  185,  314,  180,  183,  186,  184,  192,  195,
      192,  192,  192,  192,  192,  198,  199,  200,  200,  200,
      200,  200,  314,  314,  184,  314,  187,  145,  145,  145,
      145,  145,  201,  314,  201,  101,  205,  202,  202,  202,
      202,  202,  314,  314,  314,  314,  101,  314,  204,  212,
      314,  314,  314,  314,  314,  101,  101,  101,  101,  314,
      101,  314,  206,  101,  101,  101,  101,  101,  314,  314,
      211,  175,  175,  175,  175,  175,  314,  314,  314,  207,

      314,  101,  210,  314,  314,  314,  209,  175,  175,  175,
      175,  175,  314,  213,  314,  314,  101,  208,  101,  210,
      314,  314,  217,  314,  314,  101,  314,  101,  101,  314,
      314,  226,  314,  101,  101,  224,  101,  101,  314,  101,
      314,  314,  216,  192,  215,  192,  192,  192,  192,  192,
      226,  101,  224,  214,  226,  224,  219,  228,  228,  228,
      228,  228,  314,  224,  226,  216,  314,  218,  220,  229,
      314,  314,  314,  226,  202,  202,  202,  202,  202,  101,
      224,  314,  314,  227,  202,  202,  202,  202,  202,  230,
      314,  314,  314,  314,  101,  101,  314,  314,  314,  314,

      314,  314,  314,  101,  101,  231,  101,  314,  234,  101,
      234,  101,  216,  235,  236,  237,  235,  235,  314,  314,
      232,  314,  226,  314,  314,  226,  314,  314,  238,  233,
      314,  101,  101,  314,  101,  216,  101,  101,  314,  101,
      239,  314,  314,  101,  314,  226,  101,  241,  226,  244,
      314,  249,  314,  242,  174,  226,  174,  243,  226,  175,
      246,  247,  175,  175,  314,  101,  314,  248,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  250,  251,
      235,  235,  235,  252,  253,  314,  314,  314,  314,  314,
      314,  314,  269,  269,  235,  235,  235,  235,  235,  101,

      101,  101,  101,  101,  101,  261,  175,  175,  175,  262,
      314,  314,  258,  279,  279,  269,  269,  263,  314,  256,
      254,  314,  314,  259,  101,  314,  257,  175,  175,  175,
      175,  175,  314,  267,  101,  101,  314,  314,  268,  269,
      314,  314,  264,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  101,  266,  265,  314,  314,  314,  314,
      279,  314,  269,  115,  314,  314,  314,  314,  270,  101,
      101,  101,  101,  175,  175,  175,  175,  175,  101,  101,
      101,  314,  314,  314,  314,  280,  314,  314,  275,  272,
      276,  278,  314,  274,  101,  101,  101,  273,  281,  101,

      101,  175,  175,  175,  175,  175,  234,  314,  234,  314,
      314,  235,  235,  235,  235,  235,  286,  314,  285,  284,
      287,  314,  101,  279,  279,  314,  314,  314,  314,  314,
      101,  314,  314,  314,  101,  314,  314,  314,  101,  101,
      101,  101,  101,  314,  101,  101,  101,  314,  101,  101,
      296,  314,  314,  289,  314,  295,  101,  314,  314,  314,
      101,  292,  290,  293,  294,  101,  314,  101,  300,  298,
      279,  299,  301,  314,  314,  314,  314,  314,  314,  101,
      314,  314,  314,  314,  314,  303,  101,  101,  101,  101,
      101,  101,  314,  101,  307,  308,  101,  101,  304,  314,

      314,  314,  314,  309,  312,  101,  310,  314,  314,  314,
      314,  313,  311,  314,  306,   14,   14,   14,   14,   14,
       14,   14,   15,   15,   15,   15,   15,   15,   15,   70,
      314,   70,   70,   70,   70,   70,  100,  100,  100,  100,
      100,  130,  130,  130,  130,  131,  314,  131,  131,  131,
      131,  131,  133,  314,  133,  133,  133,  133,  133,  134,
      134,  203,  314,  203,  282,  314,  282,  288,  314,  288,
       13,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,

      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314
    } ;

static const flex_int16_t yy_chk[1035] =
    {   0,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    5,    5,    5,    5,    6,    6,    6,
        6,    7,    7,    7,    7,    8,    8,    8,    8,   20,
       23,   32,  302,  297,   20,   23,  291,   37,  137,  283,
      271,    5,   20,   23,   32,    6,    9,    9,    9,    9,

       37,    9,   31,   32,   87,   87,    9,  137,  260,   21,
       21,   21,   21,   21,  137,   31,   22,   22,   22,   22,
       22,    9,   21,    9,   34,    9,  255,   21,    9,   22,
      245,   32,  240,   31,   22,   21,    9,   34,    9,   35,
       43,   24,   22,   24,   24,   24,   24,   24,    9,  100,
       34,   87,   35,   43,   40,    9,   40,    9,   11,   11,
       11,   25,  100,   25,   25,   25,   25,   25,   11,   40,
       35,   36,   11,   11,   11,   11,   11,   11,   12,   12,
       12,   28,   28,  221,   36,   43,   28,  217,   12,   36,
       26,   28,   12,   12,   12,   12,   12,   12,   26,   28,

       26,   26,   26,   26,   26,   30,   33,   38,   36,   39,
       30,  197,   41,   36,   42,   30,   64,   44,   50,   33,
       38,  194,   39,   30,   33,   41,   61,   42,   47,   39,
       44,   50,  193,   64,   41,   33,   45,   64,   38,   44,
       49,   47,   46,  190,   41,   42,   39,  143,  102,   45,
       61,   65,   50,   49,   45,   46,   38,  139,   49,   47,
       46,  102,   45,   61,   46,  148,  148,   65,   89,   50,
       45,  138,  111,   89,   68,   65,   68,   68,   68,   68,
       68,   89,   49,  136,   65,  111,  135,   45,   65,  133,
      132,   74,   46,   74,   74,   74,   74,   74,   84,   84,

       84,   84,   84,   85,  131,  130,  104,   70,  111,   63,
       86,   85,  148,   85,   85,   85,   85,   85,   86,  104,
       86,   86,   86,   86,   86,   90,   94,   95,  103,  105,
       90,   94,   95,  106,  107,   62,  108,  109,   90,   94,
       95,  103,  105,   60,   59,  140,  106,  107,  110,  108,
      109,  112,  103,   53,   48,  113,  104,  108,  105,  114,
      116,  110,  140,  140,  112,  107,  109,  106,  113,  115,
       29,  115,  114,  116,  115,  115,  115,  115,  115,  110,
      117,  119,  120,  107,  121,  109,  113,  122,  125,  123,
      124,   27,  126,  117,  119,  120,  116,  121,   13,  127,

      122,  125,  123,  124,  112,  126,  129,    0,  163,    0,
      141,  122,  127,  117,    0,    0,  117,    0,  141,  129,
      121,  163,  125,    0,  120,  123,  126,  124,  134,  141,
      134,  134,  134,  134,  134,  141,  141,  142,  142,  142,
      142,  142,  162,    0,  124,    0,  127,  145,  145,  145,
      145,  145,  146,  164,  146,  162,  163,  146,  146,  146,
      146,  146,  165,  166,  167,  168,  164,  169,  162,  171,
      170,  171,  172,  173,  176,  165,  166,  167,  168,    0,
      169,    0,  164,  170,  171,  172,  173,  176,  177,    0,
      170,  174,  174,  174,  174,  174,    0,    0,    0,  166,

        0,  177,  169,  178,    0,  180,  168,  175,  175,  175,
      175,  175,  181,  176,  182,  183,  178,  167,  180,  169,
      184,  186,  185,  205,  187,  181,  185,  182,  183,    0,
        0,  198,    0,  184,  186,  195,  205,  187,  204,  185,
        0,    0,  184,  192,  183,  192,  192,  192,  192,  192,
      199,  204,  195,  180,  198,  195,  186,  200,  200,  200,
      200,  200,    0,  199,  198,  184,  206,  185,  187,  204,
        0,    0,    0,  199,  201,  201,  201,  201,  201,  206,
      199,  208,  209,  199,  202,  202,  202,  202,  202,  207,
      210,  207,    0,  211,  208,  209,  213,    0,  214,    0,

        0,    0,    0,  210,  207,  209,  211,    0,  212,  213,
      212,  214,  210,  212,  212,  212,  212,  212,  215,  216,
      209,  218,  224,  219,  220,  227,  229,    0,  213,  211,
      231,  215,  216,  232,  218,  210,  219,  220,    0,  229,
      215,    0,    0,  231,    0,  224,  232,  218,  227,  219,
        0,  232,  233,  218,  230,  224,  230,  218,  227,  230,
      230,  230,  230,  230,    0,  233,    0,  231,  234,  234,
      234,  234,  234,  235,  235,  235,  235,  235,  233,  236,
      236,  236,  236,  236,  237,    0,  238,  239,  241,  242,
      243,  244,  253,  253,  237,  237,  237,  237,  237,  238,

      239,  241,  242,  243,  244,  246,  246,  246,  246,  246,
        0,  248,  243,  263,  263,  269,  269,  247,    0,  241,
      238,  249,  250,  244,  248,    0,  242,  247,  247,  247,
      247,  247,    0,  251,  249,  250,    0,    0,  252,  253,
      254,    0,  248,  251,  251,  251,  251,  251,  252,  252,
      252,  252,  252,  254,  250,  249,  256,  257,  258,  259,
      263,    0,  269,  261,    0,  264,  265,  266,  254,  256,
      257,  258,  259,  261,  261,  261,  261,  261,  264,  265,
      266,  270,  272,  274,    0,  264,  273,  275,  258,  256,
      259,  262,    0,  257,  270,  272,  274,  256,  266,  273,

      275,  262,  262,  262,  262,  262,  267,    0,  267,  276,
        0,  267,  267,  267,  267,  267,  274,  280,  273,  272,
      275,  281,  276,  279,  279,  284,  285,  286,  287,  289,
      280,  290,  292,  293,  281,  294,  295,    0,  284,  285,
      286,  287,  289,  296,  290,  292,  293,  298,  294,  295,
      290,    0,  299,  280,  300,  289,  296,    0,    0,    0,
      298,  284,  281,  285,  286,  299,  301,  300,  295,  293,
      279,  294,  296,  303,  304,  307,  306,  308,  309,  301,
      310,    0,    0,  312,  311,  300,  303,  304,  307,  306,
      308,  309,  313,  310,  304,  306,  312,  311,  301,    0,

        0,    0,    0,  307,  311,  313,  308,    0,    0,    0,
        0,  312,  310,    0,  303,  315,  315,  315,  315,  315,
      315,  315,  316,  316,  316,  316,  316,  316,  316,  317,
        0,  317,  317,  317,  317,  317,  318,  318,  318,  318,
      318,  319,  319,  319,  319,  320,    0,  320,  320,  320,
      320,  320,  321,    0,  321,  321,  321,  321,  321,  322,
      322,  323,    0,  323,  324,    0,  324,  325,    0,  325,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,

      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#line 2 "scanner.l"

// This scanner is based on the IEC standard 61131-3 which, among other things,
// includes a BNF grammar for the Instruction List (IL) language. The
// Statement List language (STL) by Siemens complies with the standards 
// defined by the IEC, although some modifications were made for compatibility
// reasons. As a consequence, the general language structure specified by the 
// IEC is similar to the structure of STL, but there are differences between
// their syntax and some language features (In general, Siemens implements more
// language features in STL than described in the standard).

// Conversion from yytext to expressions.
#include "converters/convert_bool_literal.h"
#include "converters/convert_int_literal.h"
#include "converters/convert_dint_literal.h"
#include "converters/convert_real_literal.h"
#include "converters/convert_string_value.h"

// Disable warnings for generated file.
#include <util/pragma_wsign_compare.def>
#include <util/pragma_wnull_conversion.def>
#include <util/pragma_wdeprecated_register.def>

#include <algorithm>

// Visual Studio
#if defined _MSC_VER
// Disable warning for signed/unsigned mismatch.
#pragma warning(disable:4365)
// Disable warning for macro re-definition: Flex conditionally defines 
// INT32_MAX et al. and thus they are set before library headers get to define
// them.
#pragma warning(disable:4005)
#endif

// Conditionally disable unistd header since it does not exist when building on
// Windows. 
#ifdef _WIN32
#define YY_NO_UNISTD_H
static int isatty(int) { return 0; }
#endif

// Value inside of statement_list_parser.h.
#define PARSER statement_list_parser

// Sets the type of yystatement_listlval so that it can be used as the stack 
// index.
#define YYSTYPE unsigned

// For access to the stack and the parser itself.
#include "statement_list_parser.h"

 // To get the token types from Bison.
#include "statement_list_y.tab.h"

// Add an empty expression to the stack, set yystatement_listlval to the 
// position of that element and set the source location to the new expression.
#define loc() \
  { newstack(yystatement_listlval); \
    PARSER.set_source_location(parser_stack(yystatement_listlval)); }
  
#ifdef STATEMENT_LIST_DEBUG
extern int yystatement_listdebug;
#endif
void statement_list_scanner_init()
{
#ifdef STATEMENT_LIST_DEBUG
  yystatement_listdebug=1;
#endif
  YY_FLUSH_BUFFER;
  BEGIN(0);
}
#line 1112 "statement_list_lex.yy.cpp"
#define YY_NO_INPUT 1

#line 1115 "statement_list_lex.yy.cpp"

#define INITIAL 0
#define GRAMMAR 1
#define TAG_NAME 2
#define MODULE_NAME 3
#define TAG_ATTRIBUTES 4
#define VERSION_ANNOTATION 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 84 "scanner.l"


#line 1338 "statement_list_lex.yy.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 315 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 971 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 86 "scanner.l"
{ BEGIN(GRAMMAR);
                  yyless(0); /* start again with this character */
                }
	YY_BREAK

case 2:
YY_RULE_SETUP
#line 90 "scanner.l"
{ loc(); return yytext[0]; }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 91 "scanner.l"
;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 92 "scanner.l"
{ loc(); return TOK_ASSIGNMENT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 93 "scanner.l"
{ loc(); BEGIN(TAG_NAME); return TOK_TAG; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 94 "scanner.l"
{ loc(); return TOK_BEGIN; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 95 "scanner.l"
{ loc(); BEGIN(VERSION_ANNOTATION); return TOK_VERSION; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 96 "scanner.l"
{ loc(); BEGIN(MODULE_NAME); return TOK_FUNCTION_BLOCK; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 97 "scanner.l"
{ loc(); return TOK_END_FUNCTION_BLOCK; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 98 "scanner.l"
{ loc(); BEGIN(MODULE_NAME); return TOK_FUNCTION; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 99 "scanner.l"
{ loc(); return TOK_END_FUNCTION; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 100 "scanner.l"
{ loc(); return TOK_VAR_INPUT; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 101 "scanner.l"
{ loc(); return TOK_VAR_OUTPUT; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 102 "scanner.l"
{ loc(); return TOK_VAR_INOUT; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 103 "scanner.l"
{ loc(); return TOK_VAR_STATIC; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 104 "scanner.l"
{ loc(); return TOK_VAR_CONSTANT; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 105 "scanner.l"
{ loc(); return TOK_VAR_TEMP; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 106 "scanner.l"
{ loc(); return TOK_END_VAR; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 107 "scanner.l"
{ loc(); return TOK_NETWORK; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 108 "scanner.l"
{ loc(); return TOK_TITLE; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 109 "scanner.l"
{ loc(); return TOK_INT; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 110 "scanner.l"
{ loc(); return TOK_DINT; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 111 "scanner.l"
{ loc(); return TOK_BOOL; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 112 "scanner.l"
{ loc(); return TOK_REAL; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 113 "scanner.l"
{ loc(); return TOK_VOID; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 114 "scanner.l"
{ loc(); return TOK_LOAD; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 115 "scanner.l"
{ loc(); return TOK_TRANSFER; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 116 "scanner.l"
{ loc(); BEGIN(MODULE_NAME); return TOK_CALL; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 117 "scanner.l"
{ loc(); return TOK_NOP; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 118 "scanner.l"
{ loc(); return TOK_SET_RLO; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 119 "scanner.l"
{ loc(); return TOK_CLR_RLO; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 120 "scanner.l"
{ loc(); return TOK_SET; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 121 "scanner.l"
{ loc(); return TOK_RESET; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 122 "scanner.l"
{ loc(); return TOK_NOT; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 123 "scanner.l"
{ loc(); return TOK_AND; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 124 "scanner.l"
{ loc(); return TOK_AND_NOT; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 125 "scanner.l"
{ loc(); return TOK_OR; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 126 "scanner.l"
{ loc(); return TOK_OR_NOT; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 127 "scanner.l"
{ loc(); return TOK_XOR; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 128 "scanner.l"
{ loc(); return TOK_XOR_NOT; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 129 "scanner.l"
{ loc(); return TOK_AND_NESTED; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 130 "scanner.l"
{ loc(); return TOK_AND_NOT_NESTED; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 131 "scanner.l"
{ loc(); return TOK_OR_NESTED; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 132 "scanner.l"
{ loc(); return TOK_OR_NOT_NESTED; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 133 "scanner.l"
{ loc(); return TOK_XOR_NESTED; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 134 "scanner.l"
{ loc(); return TOK_XOR_NOT_NESTED; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 135 "scanner.l"
{ loc(); return TOK_NESTING_CLOSED; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 136 "scanner.l"
{ loc(); return TOK_ASSIGN; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 137 "scanner.l"
{ loc(); return TOK_CONST_ADD; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 138 "scanner.l"
{ loc(); return TOK_ACCU_INT_ADD; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 139 "scanner.l"
{ loc(); return TOK_ACCU_INT_SUB; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 140 "scanner.l"
{ loc(); return TOK_ACCU_INT_MUL; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 141 "scanner.l"
{ loc(); return TOK_ACCU_INT_DIV; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 142 "scanner.l"
{ loc(); return TOK_ACCU_INT_EQ; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 143 "scanner.l"
{ loc(); return TOK_ACCU_INT_NEQ; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 144 "scanner.l"
{ loc(); return TOK_ACCU_INT_GT; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 145 "scanner.l"
{ loc(); return TOK_ACCU_INT_LT; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 146 "scanner.l"
{ loc(); return TOK_ACCU_INT_GTE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 147 "scanner.l"
{ loc(); return TOK_ACCU_INT_LTE; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 148 "scanner.l"
{ loc(); return TOK_ACCU_REAL_ADD; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 149 "scanner.l"
{ loc(); return TOK_ACCU_REAL_SUB; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 150 "scanner.l"
{ loc(); return TOK_ACCU_REAL_MUL; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 151 "scanner.l"
{ loc(); return TOK_ACCU_REAL_DIV; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 152 "scanner.l"
{ loc(); return TOK_ACCU_REAL_EQ; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 153 "scanner.l"
{ loc(); return TOK_ACCU_REAL_NEQ; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 154 "scanner.l"
{ loc(); return TOK_ACCU_REAL_GT; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 155 "scanner.l"
{ loc(); return TOK_ACCU_REAL_LT; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 156 "scanner.l"
{ loc(); return TOK_ACCU_REAL_GTE; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 157 "scanner.l"
{ loc(); return TOK_ACCU_REAL_LTE; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 158 "scanner.l"
{ loc(); return TOK_ACCU_DINT_ADD; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 159 "scanner.l"
{ loc(); return TOK_ACCU_DINT_SUB; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 160 "scanner.l"
{ loc(); return TOK_ACCU_DINT_MUL; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 161 "scanner.l"
{ loc(); return TOK_ACCU_DINT_DIV; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 162 "scanner.l"
{ loc(); return TOK_ACCU_DINT_EQ; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 163 "scanner.l"
{ loc(); return TOK_ACCU_DINT_NEQ; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 164 "scanner.l"
{ loc(); return TOK_ACCU_DINT_GT; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 165 "scanner.l"
{ loc(); return TOK_ACCU_DINT_LT; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 166 "scanner.l"
{ loc(); return TOK_ACCU_DINT_GTE; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 167 "scanner.l"
{ loc(); return TOK_ACCU_DINT_LTE; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 168 "scanner.l"
{ loc(); return TOK_JUMP_UNCONDITIONAL; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 169 "scanner.l"
{ loc(); return TOK_JUMP_CONDITIONAL; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 170 "scanner.l"
{ loc(); return TOK_JUMP_CONDITIONAL_NOT; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 172 "scanner.l"
{ 
                        newstack(yystatement_listlval);
                        parser_stack(yystatement_listlval) = 
                          convert_int_dec_literal(yytext);
                        PARSER.set_source_location(
                          parser_stack(yystatement_listlval));
                        return TOK_INT_LITERAL; 
                      }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 180 "scanner.l"
{ 
                        newstack(yystatement_listlval);
                        parser_stack(yystatement_listlval) = 
                          convert_int_dec_literal_value(yytext);
                        PARSER.set_source_location(
                          parser_stack(yystatement_listlval));
                        return TOK_INT_LITERAL; 
                      }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 189 "scanner.l"
{ 
                        newstack(yystatement_listlval);
                        parser_stack(yystatement_listlval) = 
                          convert_dint_dec_literal_value(yytext);
                        PARSER.set_source_location(
                          parser_stack(yystatement_listlval));
                        return TOK_INT_LITERAL; 
                      }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 198 "scanner.l"
{ 
                        newstack(yystatement_listlval);
                        parser_stack(yystatement_listlval) = 
                          convert_int_hex_literal(yytext);
                        PARSER.set_source_location(
                          parser_stack(yystatement_listlval));
                        return TOK_INT_LITERAL; 
                      }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 206 "scanner.l"
{ 
                        newstack(yystatement_listlval);
                        parser_stack(yystatement_listlval) = 
                          convert_int_hex_literal_value(yytext);
                        PARSER.set_source_location(
                          parser_stack(yystatement_listlval));
                        return TOK_INT_LITERAL; 
                      }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 215 "scanner.l"
{ 
                        newstack(yystatement_listlval);
                        parser_stack(yystatement_listlval) = 
                          convert_dint_hex_literal_value(yytext);
                        PARSER.set_source_location(
                          parser_stack(yystatement_listlval));
                        return TOK_INT_LITERAL; 
                      }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 224 "scanner.l"
{ 
                        newstack(yystatement_listlval);
                        parser_stack(yystatement_listlval) = 
                          convert_int_bit_literal(yytext);
                        PARSER.set_source_location(
                          parser_stack(yystatement_listlval));
                        return TOK_INT_LITERAL; 
                      }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 233 "scanner.l"
{
                        newstack(yystatement_listlval);
                        parser_stack(yystatement_listlval) = 
                          convert_int_bit_literal_value(yytext);
                        PARSER.set_source_location(
                          parser_stack(yystatement_listlval));
                        return TOK_INT_LITERAL; 
                      }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 242 "scanner.l"
{
                        newstack(yystatement_listlval);
                        parser_stack(yystatement_listlval) = 
                          convert_dint_bit_literal_value(yytext);
                        PARSER.set_source_location(
                          parser_stack(yystatement_listlval));
                        return TOK_INT_LITERAL; 
                      }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 251 "scanner.l"
{ 
                        newstack(yystatement_listlval);
                        parser_stack(yystatement_listlval) = 
                          convert_bool_literal(yytext);
                        PARSER.set_source_location(
                          parser_stack(yystatement_listlval));
                        return TOK_BOOL_LITERAL; 
                      }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 260 "scanner.l"
{
                        newstack(yystatement_listlval);
                        parser_stack(yystatement_listlval) = 
                          convert_real_literal(yytext);
                        PARSER.set_source_location(
                          parser_stack(yystatement_listlval));
                        return TOK_REAL_LITERAL; 
                      }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 269 "scanner.l"
{
                        newstack(yystatement_listlval);
                        parser_stack(yystatement_listlval) = 
                          convert_identifier(yytext);
                        PARSER.set_source_location(
                          parser_stack(yystatement_listlval));
                        return TOK_IDENTIFIER; 
                      }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 278 "scanner.l"
{
                        newstack(yystatement_listlval);
                        parser_stack(yystatement_listlval) = 
                          convert_label(yytext);
                        PARSER.set_source_location(
                          parser_stack(yystatement_listlval));
                        return TOK_LABEL;
                      }
	YY_BREAK


case 96:
/* rule 96 can match eol */
YY_RULE_SETUP
#line 289 "scanner.l"
;
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 290 "scanner.l"
{
                        newstack(yystatement_listlval);
                        parser_stack(yystatement_listlval) = 
                          convert_identifier(yytext);
                        PARSER.set_source_location(
                          parser_stack(yystatement_listlval));
                        BEGIN(TAG_ATTRIBUTES);
                        return TOK_IDENTIFIER; 
                      }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 299 "scanner.l"
{ loc(); BEGIN(GRAMMAR); return TOK_END_TAG; }
	YY_BREAK


case 99:
/* rule 99 can match eol */
YY_RULE_SETUP
#line 303 "scanner.l"
;
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 304 "scanner.l"
{
                        newstack(yystatement_listlval);
                        std::string str{yytext};
                        str.erase(
                          std::remove(begin(str), end(str), '\"' ), 
                          end(str));
                        parser_stack(yystatement_listlval) = 
                          convert_identifier(str);
                        PARSER.set_source_location(
                          parser_stack(yystatement_listlval));
                        BEGIN(GRAMMAR);
                        return TOK_IDENTIFIER; 
                      }
	YY_BREAK


case 101:
YY_RULE_SETUP
#line 320 "scanner.l"
;
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 321 "scanner.l"
;
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 322 "scanner.l"
;
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 323 "scanner.l"
{ loc(); return TOK_INT; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 324 "scanner.l"
{ loc(); return TOK_DINT; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 325 "scanner.l"
{ loc(); return TOK_BOOL; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 326 "scanner.l"
{ loc(); return TOK_REAL; }
	YY_BREAK
case 108:
/* rule 108 can match eol */
YY_RULE_SETUP
#line 327 "scanner.l"
{ BEGIN(TAG_NAME); } 
	YY_BREAK


case 109:
YY_RULE_SETUP
#line 331 "scanner.l"
;
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 332 "scanner.l"
{ loc(); return yytext[0]; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 333 "scanner.l"
{
                        newstack(yystatement_listlval);
                        parser_stack(yystatement_listlval) =
                          convert_version(yytext);
                        PARSER.set_source_location(
                          parser_stack(yystatement_listlval));
                        return TOK_VERSION_VALUE;
                      }
	YY_BREAK
case 112:
/* rule 112 can match eol */
YY_RULE_SETUP
#line 341 "scanner.l"
{ BEGIN(GRAMMAR); }
	YY_BREAK

case 113:
YY_RULE_SETUP
#line 343 "scanner.l"
ECHO;
	YY_BREAK
#line 2096 "statement_list_lex.yy.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(GRAMMAR):
case YY_STATE_EOF(TAG_NAME):
case YY_STATE_EOF(MODULE_NAME):
case YY_STATE_EOF(TAG_ATTRIBUTES):
case YY_STATE_EOF(VERSION_ANNOTATION):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 315 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 315 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 314);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 343 "scanner.l"


